### PR TITLE
Rewrite Flask API with AWS Ruby SDK for the new version of the streamer

### PR DESCRIPTION
**Pull request by utanashati**

### CODE REVIEW

**Comment by mar-muel** [comment]
🎉

**Comment by utanashati** [comment]
@mar-muel Thanks! Still not building on Heroku staging though:
```
ERROR in ./app/javascript/custom/rollbar.js.erb
       Module build failed (from ./node_modules/rails-erb-loader/index.js):
       Error: rails-erb-loader failed with code: 1
           at ChildProcess.<anonymous> (/tmp/build_a91e964b/node_modules/rails-erb-loader/index.js:128:16)
           at ChildProcess.emit (events.js:310:20)
           at maybeClose (internal/child_process.js:1021:16)
           at Socket.<anonymous> (internal/child_process.js:443:11)
           at Socket.emit (events.js:310:20)
           at Pipe.<anonymous> (net.js:672:12)
        @ ./app/javascript/custom/index.js 2:0-18
        @ ./app/javascript/packs/application.js
```

Weird, I didn't even change the file.

**Comment by mar-muel** [comment]
hmm feels familiar. You might want to completely ditch Rollbar and move to Sentry like the rest of the team? @noefroidevaux

**Comment by utanashati** [comment]
I'll look into it, thanks!

**Comment by utanashati** [comment]
Actually, now it's worked, a completely unrelated thing fixed it somehow.

**Pull request merged**
